### ISSUE TITLE
Don't bundle certain libraries

### ISSUE THREAD

**Issue by probonopd** [martinribelotta/embedded-ide-builder#1]
The AppImage currently bundles private copies of 
* librt.so.1
* libusb-1.0.so.0

This is not recommended, as these libraries can be assumed to be present on most target systems.

Are you sure you need to privately bundle them?

Furthermore, we get 

```
embedded-ide: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found 
```

Can you lower the libstdc++.so.6 version requirement so that the AppImage would run on Ubuntu trusty?

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266067850

**Comment by martinribelotta** [comment]
Rearrange bundle libraries is WiP.
libstdc++.so.6 is more complicated. Need a build env with a lower library systems like RHEL 6 or less.
Any sugerence?

**Comment by probonopd** [comment]
Building on Ubuntu 14.04 may be an option, as long as you don't pull in newer libstdc++.so.6 through PPAs or external repositories.

**Comment by probonopd** [comment]
Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 and https://github.com/darealshinji/AppImageKit-checkrt/. I have been using it with success for https://github.com/probonopd/audacity/releases to bundle a newer `libstdc++.so.6` than the one that comes with Ubuntu 14.04.

**Comment by martinribelotta** [comment]
@probonopd I've been seeing that solution the previous days.
For now, my approach is to use Docker with ubuntu 14.04.
Aparently, this work fine but need more testings.
If you can try to test It, you can download from https://drive.google.com/file/d/1HjRb66SuId4zjOLKrUNM8HSwJxwKJZO7/view?usp=sharing

**Comment by probonopd** [comment]
Thanks @martinribelotta, it runs on `xubuntu-16.04.1-desktop-amd64.iso`:

![](https://user-images.githubusercontent.com/2480569/35167669-4591cf38-fd4e-11e7-941e-1b7216c31f93.png)

**Comment by martinribelotta** [comment]
@probonopd I just saw this: https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#testing and try to test with more live CD iso

**Comment by martinribelotta** [comment]
This issue is resolved in the last commit

**Comment by probonopd** [comment]
@Restarted tests at https://travis-ci.org/AppImage/appimage.github.io/builds/337169360
